development:
  repositories:
    default: couchdb://localhost:5984/muddle_development
    mysql:
      adapter: mysql
      database: muddle_development
      host: localhost
      username: root

test:
  repositories:
    default: couchdb://localhost:5984/muddle_test
    mysql:
      adapter: mysql
      database: muddle_test
      host: localhost
      username: root

production:
  repositories:
    default: couchdb://localhost:5984/muddle
    mysql:
      adapter: mysql
      database: muddle
      host: localhost
      username: root
